### ISSUE TITLE
An alternative use for lambdas

### ISSUE THREAD

**Issue by ravernkoh** [Kaioru/np-python-notes#1]
In your notes, you mentioned lambdas are used for quick throwaway variables. I offer an alternative use case for lambdas.

Lambdas are anonymous functions, meaning that they are usually used for functions that are only meant to be used once in a program. For example, here is a use case with the map function:
```python
list = [1, 2, 3, 4, 5]
new_list = map(lambda x: x * x, list)
print(new_list)
# This outputs: [1, 4, 9, 16, 25]
```

As can be seen, this lambda was actually a function that takes a single input, squares it and returns the result. Its basically the same as this:
```python
def square(x):
    return x * x

list = [1, 2, 3, 4, 5]
new_list = map(square, list)
print(new_list)
# This outputs: [1, 4, 9, 16, 25]
```

However, I am only going to use the function `square` once in my program, **and** its a simple function, so I don't really need to name it. Thus I decided to use an anonymous function, or as Python calls it, a lambda.

**Comment by Kaioru** [comment]
Yeah, I didn't really go in-depth for Lambdas but this is pretty much spot on.
I'll probably be updating it soon(tm), feel free to create a PR though.
